// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsfrjojomgotelkgiltv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZnJqb2pvbWdvdGVsa2dpbHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDg0MTcsImV4cCI6MjA1OTg4NDQxN30.PWgrF6OEqejvNALr_tMNXRmHuvBEZvX7dcsj822AwkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);